
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Munseon Kim  ## put your name
title: 'WEB DEVELOPER &amp; QA'  ## your title
location: Gyeonggi-do , KOREA  ## 내위치


## Social Profiles
facebook: http://www.facebook.com/k.moonsun94  ## your facebook account url 페이스북
naver: https://blog.naver.com/jenny2103  ## your naver blog account url 네이버 블로그
linkedin: http://www.linkedin.com/in/moonsun94  ## your linkedin account url www.linkedin.com 링크드인
instagram: http://www.instagram.com/sun25th ## you instagram account url 인스타그램
github: http://www.github.com/moonsunkim94  ## your github account url 깃허브



# Update all the sections by editing the files inside _includes folder.
